# Copyright (C) 2025 milrt <milrt@proton.me>
# SPDX-License-Identifier: GPL-3.0-or-later

set(SECP256K1_ENABLE_MODULE_ECDH         OFF CACHE BOOL "Enable ECDH in secp256k1" FORCE)
set(SECP256K1_ENABLE_MODULE_RECOVERY     ON CACHE BOOL "Enable recovery in secp256k1" FORCE)
set(SECP256K1_ENABLE_MODULE_EXTRAKEYS    OFF CACHE BOOL "Disable extra keys" FORCE)
set(SECP256K1_ENABLE_MODULE_SCHNORRSIG   OFF CACHE BOOL "Enable Schnorr signatures in secp256k1" FORCE)
set(SECP256K1_ENABLE_MODULE_ELLSWIFT     OFF CACHE BOOL "Enable Elliptic Swift module" FORCE)
set(SECP256K1_ENABLE_MODULE_GENERATOR    OFF CACHE BOOL "Enable generator module" FORCE)
set(SECP256K1_ENABLE_MODULE_RANGEPROOF   OFF CACHE BOOL "Enable range proof module" FORCE)
set(SECP256K1_ENABLE_MODULE_SURJECTIONPROOF OFF CACHE BOOL "Enable surjection proof module" FORCE)
set(SECP256K1_ENABLE_MODULE_WHITELIST    OFF CACHE BOOL "Enable whitelist module" FORCE)
set(SECP256K1_ENABLE_MODULE_MUSIG        OFF CACHE BOOL "Enable MuSig module" FORCE)
set(SECP256K1_ENABLE_MODULE_ECDSA_ADAPTOR OFF CACHE BOOL "Enable ECDSA adaptor signatures" FORCE)
set(SECP256K1_ENABLE_MODULE_ECDSA_S2C    OFF CACHE BOOL "Enable ECDSA Sign-to-contract module" FORCE)
set(SECP256K1_ENABLE_MODULE_BPPP         OFF CACHE BOOL "Enable Bulletproofs+ module" FORCE)
set(SECP256K1_BUILD_BENCHMARK            OFF CACHE BOOL "Disable building benchmarks" FORCE)
set(SECP256K1_BUILD_TESTS                OFF CACHE BOOL "Disable building tests" FORCE)
set(SECP256K1_BUILD_EXHAUSTIVE_TESTS     OFF CACHE BOOL "Disable building exhaustive tests" FORCE)
set(SECP256K1_BUILD_CTIME_TESTS          OFF CACHE BOOL "Disable building ctime tests" FORCE)
set(SECP256K1_BUILD_EXAMPLES             OFF CACHE BOOL "Disable building examples" FORCE)
set(SECP256K1_ECMULT_WINDOW_SIZE         2 CACHE STRING "Set ECMULT window size" FORCE)
set(SECP256K1_ECMULT_GEN_KB              2 CACHE STRING "Set ECMULT generator size in KB" FORCE)
set(BUILD_SHARED_LIBS                    OFF CACHE BOOL "Build shared libraries" FORCE)
